package com.directv.mlb.pojo;

// Generated Dec 8, 2014 5:40:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Gamedetail generated by hbm2java
 */
@Entity
@Table(name = "GAMEDETAIL", uniqueConstraints = @UniqueConstraint(columnNames = { "GAMEID", "DATASOURCE" }))
@SequenceGenerator(name = "S_GAMEDETAILID", sequenceName = "S_GAMEDETAILID")
public class Gamedetail implements java.io.Serializable {

    private Integer gamedetailid;

    private Date timestamp;

    private Game game;

    private String datasource;

    private String externalgamepk;

    private String externalgameid;

    private String externalbatterid;

    private String externalpitcherid;

    private String celllabelstate;

    private String gamestatus;

    private String gamestatusreason;

    private Short inning;

    private String inningsegment;

    private Short runneronfirst;

    private Short runneronsecond;

    private Short runneronthird;

    private Short balls;

    private Short strikes;

    private Short outs;

    private Short hometeamhits;

    private Short awayteamhits;

    private Short hometeamruns;

    private Short awayteamruns;

    private Short hometeamerrors;

    private Short awayteamerrors;

    private Short homebattingposition;

    private Short awaybattingposition;

    private Date created;

    private String createdby;

    private Date updated;

    private String updatedby;

    private Set<Inning> innings = new HashSet<Inning>(0);

    public Gamedetail() {
    }

    @Id
    @Column(name = "GAMEDETAILID", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "S_GAMEDETAILID")
    public Integer getGamedetailid() {
        return this.gamedetailid;
    }

    public void setGamedetailid(Integer gamedetailid) {
        this.gamedetailid = gamedetailid;
    }

    @Version
    @Column(name = "TIMESTAMP", nullable = false)
    public Date getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GAMEID", nullable = false)
    public Game getGame() {
        return this.game;
    }

    public void setGame(Game game) {
        this.game = game;
    }

    @Column(name = "DATASOURCE", nullable = false, length = 28)
    public String getDatasource() {
        return this.datasource;
    }

    public void setDatasource(String datasource) {
        this.datasource = datasource;
    }

    @Column(name = "EXTERNALGAMEPK", length = 120)
    public String getExternalgamepk() {
        return this.externalgamepk;
    }

    public void setExternalgamepk(String externalgamepk) {
        this.externalgamepk = externalgamepk;
    }

    @Column(name = "EXTERNALGAMEID", length = 120)
    public String getExternalgameid() {
        return this.externalgameid;
    }

    public void setExternalgameid(String externalgameid) {
        this.externalgameid = externalgameid;
    }

    @Column(name = "EXTERNALBATTERID", length = 120)
    public String getExternalbatterid() {
        return this.externalbatterid;
    }

    public void setExternalbatterid(String externalbatterid) {
        this.externalbatterid = externalbatterid;
    }

    @Column(name = "EXTERNALPITCHERID", length = 120)
    public String getExternalpitcherid() {
        return this.externalpitcherid;
    }

    public void setExternalpitcherid(String externalpitcherid) {
        this.externalpitcherid = externalpitcherid;
    }

    @Column(name = "CELLLABELSTATE", length = 240)
    public String getCelllabelstate() {
        return this.celllabelstate;
    }

    public void setCelllabelstate(String celllabelstate) {
        this.celllabelstate = celllabelstate;
    }

    @Column(name = "GAMESTATUS", length = 40)
    public String getGamestatus() {
        return this.gamestatus;
    }

    public void setGamestatus(String gamestatus) {
        this.gamestatus = gamestatus;
    }

    @Column(name = "GAMESTATUSREASON", length = 120)
    public String getGamestatusreason() {
        return this.gamestatusreason;
    }

    public void setGamestatusreason(String gamestatusreason) {
        this.gamestatusreason = gamestatusreason;
    }

    @Column(name = "INNING")
    public Short getInning() {
        return this.inning;
    }

    public void setInning(Short inning) {
        this.inning = inning;
    }

    @Column(name = "INNINGSEGMENT", length = 24)
    public String getInningsegment() {
        return this.inningsegment;
    }

    public void setInningsegment(String inningsegment) {
        this.inningsegment = inningsegment;
    }

    @Column(name = "RUNNERONFIRST")
    public Short getRunneronfirst() {
        return this.runneronfirst;
    }

    public void setRunneronfirst(Short runneronfirst) {
        this.runneronfirst = runneronfirst;
    }

    @Column(name = "RUNNERONSECOND")
    public Short getRunneronsecond() {
        return this.runneronsecond;
    }

    public void setRunneronsecond(Short runneronsecond) {
        this.runneronsecond = runneronsecond;
    }

    @Column(name = "RUNNERONTHIRD")
    public Short getRunneronthird() {
        return this.runneronthird;
    }

    public void setRunneronthird(Short runneronthird) {
        this.runneronthird = runneronthird;
    }

    @Column(name = "BALLS")
    public Short getBalls() {
        return this.balls;
    }

    public void setBalls(Short balls) {
        this.balls = balls;
    }

    @Column(name = "STRIKES")
    public Short getStrikes() {
        return this.strikes;
    }

    public void setStrikes(Short strikes) {
        this.strikes = strikes;
    }

    @Column(name = "OUTS")
    public Short getOuts() {
        return this.outs;
    }

    public void setOuts(Short outs) {
        this.outs = outs;
    }

    @Column(name = "HOMETEAMHITS")
    public Short getHometeamhits() {
        return this.hometeamhits;
    }

    public void setHometeamhits(Short hometeamhits) {
        this.hometeamhits = hometeamhits;
    }

    @Column(name = "AWAYTEAMHITS")
    public Short getAwayteamhits() {
        return this.awayteamhits;
    }

    public void setAwayteamhits(Short awayteamhits) {
        this.awayteamhits = awayteamhits;
    }

    @Column(name = "HOMETEAMRUNS")
    public Short getHometeamruns() {
        return this.hometeamruns;
    }

    public void setHometeamruns(Short hometeamruns) {
        this.hometeamruns = hometeamruns;
    }

    @Column(name = "AWAYTEAMRUNS")
    public Short getAwayteamruns() {
        return this.awayteamruns;
    }

    public void setAwayteamruns(Short awayteamruns) {
        this.awayteamruns = awayteamruns;
    }

    @Column(name = "HOMETEAMERRORS")
    public Short getHometeamerrors() {
        return this.hometeamerrors;
    }

    public void setHometeamerrors(Short hometeamerrors) {
        this.hometeamerrors = hometeamerrors;
    }

    @Column(name = "AWAYTEAMERRORS")
    public Short getAwayteamerrors() {
        return this.awayteamerrors;
    }

    public void setAwayteamerrors(Short awayteamerrors) {
        this.awayteamerrors = awayteamerrors;
    }

    @Column(name = "HOMEBATTINGPOSITION")
    public Short getHomebattingposition() {
        return this.homebattingposition;
    }

    public void setHomebattingposition(Short homebattingposition) {
        this.homebattingposition = homebattingposition;
    }

    @Column(name = "AWAYBATTINGPOSITION")
    public Short getAwaybattingposition() {
        return this.awaybattingposition;
    }

    public void setAwaybattingposition(Short awaybattingposition) {
        this.awaybattingposition = awaybattingposition;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED", nullable = false, length = 7)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "CREATEDBY", nullable = false, length = 240)
    public String getCreatedby() {
        return this.createdby;
    }

    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED", nullable = false, length = 7)
    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    @Column(name = "UPDATEDBY", nullable = false, length = 240)
    public String getUpdatedby() {
        return this.updatedby;
    }

    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "gamedetail")
    public Set<Inning> getInnings() {
        return this.innings;
    }

    public void setInnings(Set<Inning> innings) {
        this.innings = innings;
    }

}
