package com.directv.mlb.pojo;

// Generated Dec 8, 2014 5:40:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Gamemixgroup generated by hbm2java
 */
@Entity
@Table(name = "GAMEMIXGROUP")
@SequenceGenerator(name = "S_GAMEMIXGROUPID", sequenceName = "S_GAMEMIXGROUPID")
public class Gamemixgroup implements java.io.Serializable {

    private Integer gamemixgroupid;

    private Date timestamp;

    private String fullname;

    private Date activedate;

    private Boolean isscheduled;

    private String gamemixstate;

    private String status;

    private Date created;

    private String createdby;

    private Date updated;

    private String updatedby;

    private Integer numcells;

    private Set<Gamemix> gamemixes = new HashSet<Gamemix>(0);

    public Gamemixgroup() {
    }

    @Id
    @Column(name = "GAMEMIXGROUPID", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "S_GAMEMIXGROUPID")
    public Integer getGamemixgroupid() {
        return this.gamemixgroupid;
    }

    public void setGamemixgroupid(Integer gamemixgroupid) {
        this.gamemixgroupid = gamemixgroupid;
    }

    @Version
    @Column(name = "TIMESTAMP", nullable = false)
    public Date getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    @Column(name = "FULLNAME", nullable = false, length = 240)
    public String getFullname() {
        return this.fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ACTIVEDATE", nullable = false, length = 7)
    public Date getActivedate() {
        return this.activedate;
    }

    public void setActivedate(Date activedate) {
        this.activedate = activedate;
    }

    @Column(name = "ISSCHEDULED", nullable = false)
    public Boolean getIsscheduled() {
        return this.isscheduled;
    }

    public void setIsscheduled(Boolean isscheduled) {
        this.isscheduled = isscheduled;
    }

    @Column(name = "GAMEMIXSTATE", length = 40)
    public String getGamemixstate() {
        return this.gamemixstate;
    }

    public void setGamemixstate(String gamemixstate) {
        this.gamemixstate = gamemixstate;
    }

    @Column(name = "STATUS", nullable = false, length = 32)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED", nullable = false, length = 7)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "CREATEDBY", nullable = false, length = 240)
    public String getCreatedby() {
        return this.createdby;
    }

    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED", nullable = false, length = 7)
    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    @Column(name = "UPDATEDBY", nullable = false, length = 240)
    public String getUpdatedby() {
        return this.updatedby;
    }

    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "gamemixgroup")
    public Set<Gamemix> getGamemixes() {
        return this.gamemixes;
    }

    public void setGamemixes(Set<Gamemix> gamemixes) {
        this.gamemixes = gamemixes;
    }

    /**
     * Get numcells
     *
     * @return numcells
     */
    @Column(name = "NUMCELLS", nullable = true)
    public Integer getNumcells() {
        return numcells;
    }

    /**
     * Set numcells
     *
     * @param numcells
     *            the numcells to set
     */
    public void setNumcells(Integer numcells) {
        this.numcells = numcells;
    }

}
