package com.directv.mlb.pojo;

// Generated Dec 16, 2014 5:06:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Jobrole generated by hbm2java
 */
@Entity
@Table(name = "JOBROLE", uniqueConstraints = @UniqueConstraint(columnNames = "JOBROLE"))
@SequenceGenerator(name = "S_JOBROLEID", sequenceName = "S_JOBROLEID")
public class Jobrole implements java.io.Serializable {

    private Integer jobroleid;

    private Date timestamp;

    private String jobrole;

    private String description;

    private Date created;

    private String createdby;

    private Date updated;

    private String updatedby;

    private Set<Jobactivity> jobactivities = new HashSet<Jobactivity>(0);

    private Set<Employee> employees = new HashSet<Employee>(0);

    public Jobrole() {
    }

    @Id
    @Column(name = "JOBROLEID", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "S_JOBROLEID")
    public Integer getJobroleid() {
        return this.jobroleid;
    }

    public void setJobroleid(Integer jobroleid) {
        this.jobroleid = jobroleid;
    }

    @Version
    @Column(name = "TIMESTAMP", nullable = false)
    public Date getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    @Column(name = "JOBROLE", unique = true, nullable = false, length = 240)
    public String getJobrole() {
        return this.jobrole;
    }

    public void setJobrole(String jobrole) {
        this.jobrole = jobrole;
    }

    @Column(name = "DESCRIPTION", nullable = false, length = 1020)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED", nullable = false, length = 7)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "CREATEDBY", nullable = false, length = 240)
    public String getCreatedby() {
        return this.createdby;
    }

    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED", nullable = false, length = 7)
    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    @Column(name = "UPDATEDBY", nullable = false, length = 240)
    public String getUpdatedby() {
        return this.updatedby;
    }

    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "JOBROLEJOBACTIVITY", joinColumns = { @JoinColumn(name = "JOBROLEID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "JOBACTIVITYID", nullable = false, updatable = false) })
    public Set<Jobactivity> getJobactivities() {
        return this.jobactivities;
    }

    public void setJobactivities(Set<Jobactivity> jobactivities) {
        this.jobactivities = jobactivities;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "jobroles")
    public Set<Employee> getEmployees() {
        return this.employees;
    }

    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }

}
