package com.directv.mlb.pojo;

//Generated Dec 8, 2014 5:40:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Gamemixelement generated by hbm2java
 */
@Entity
@Table(name = "GAMEMIXELEMENT")
@SequenceGenerator(name = "S_GAMEMIXELEMENTID", sequenceName = "S_GAMEMIXELEMENTID")
public class Gamemixelement implements java.io.Serializable {

    private Integer gamemixelementid;

    private Date timestamp;

    private Game game;

    private Gamemix gamemix;

    private String position;

    private Date created;

    private String createdby;

    private Date updated;

    private String updatedby;

    public Gamemixelement() {
    }

    @Id
    @Column(name = "GAMEMIXELEMENTID", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "S_GAMEMIXELEMENTID")
    public Integer getGamemixelementid() {
        return this.gamemixelementid;
    }

    public void setGamemixelementid(Integer gamemixelementid) {
        this.gamemixelementid = gamemixelementid;
    }

    @Version
    @Column(name = "TIMESTAMP", nullable = false)
    public Date getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "GAMEID", nullable = false)
    public Game getGame() {
        return this.game;
    }

    public void setGame(Game game) {
        this.game = game;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GAMEMIXID", nullable = false)
    public Gamemix getGamemix() {
        return this.gamemix;
    }

    public void setGamemix(Gamemix gamemix) {
        this.gamemix = gamemix;
    }

    @Column(name = "POSITION", nullable = false, length = 40)
    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED", nullable = false, length = 7)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "CREATEDBY", nullable = false, length = 240)
    public String getCreatedby() {
        return this.createdby;
    }

    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED", nullable = false, length = 7)
    public Date getUpdated() {
        return this.updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    @Column(name = "UPDATEDBY", nullable = false, length = 240)
    public String getUpdatedby() {
        return this.updatedby;
    }

    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

}
